// api/manage-booking.js
// Customer-facing booking management endpoint.
//
// Allows customers to view and modify their reservation after paying a deposit.
// Authentication is via a short-lived HMAC-signed manage_token (not an admin secret).
//
// POST /api/manage-booking
// Actions (all require a valid manage_token in the request body):
//   get                — load booking details for the customer portal
//   check_availability — preview a proposed change (availability + new pricing)
//   apply_change       — apply a free first change (change_count === 0)
//   initiate_paid_change — store the pending change and create a Stripe PI for the fee
//
// Required environment variables:
//   OTP_SECRET         — signs / verifies manage tokens
//   STRIPE_SECRET_KEY  — for initiate_paid_change
//   STRIPE_PUBLISHABLE_KEY
//   SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY — Supabase admin client
//   GITHUB_TOKEN / GITHUB_REPO              — booked-dates.json updates

import Stripe from "stripe";
import nodemailer from "nodemailer";
import { createManageToken, verifyManageToken } from "./_manage-booking-token.js";
import { getSupabaseAdmin } from "./_supabase.js";
import { hasDateTimeOverlap } from "./_availability.js";
import { updateBooking, loadBookings } from "./_bookings.js";
import { updateJsonFileWithRetry } from "./_github-retry.js";
import { autoUpsertBooking, writeAuditLog, autoCreateBlockedDate, extendBlockedDateForBooking } from "./_booking-automation.js";
import { normalizeVehicleId, uiVehicleId } from "./_vehicle-id.js";
import { getVehicleById } from "./_vehicles.js";
import { fetchPaymentPlanSummary } from "./_payment-plan-summary.js";
import { getLedgerSummary } from "./_renter-balance-ledger.js";
import { deriveBookingPaymentLifecycle } from "./_booking-payment-lifecycle.js";
import {
  loadPricingSettings,
  computeDppCostFromSettings,
  applyTax,
} from "./_settings.js";
import { computeRentalDays, getVehiclePricing, computeAmountFromPricing } from "./_pricing.js";
import { normalizeClockTime } from "./_time.js";
import {
  createRenterSessionToken,
  extractBearerToken,
  verifyRenterSessionToken,
} from "./_renter-auth.js";
import { loadAgreementPathForDownload, loadBookingAgreementSummary } from "./_agreement-automation.js";

const ALLOWED_ORIGINS    = ["https://www.slytrans.com", "https://slytrans.com", "https://slycarrentals.com", "https://www.slycarrentals.com", "https://admin.slycarrentals.com", "https://sly-rides.vercel.app"];
const GITHUB_REPO        = process.env.GITHUB_REPO || "kysboadi-afk/SLY-RIDES";
const GITHUB_DATA_BRANCH = process.env.GITHUB_DATA_BRANCH || "main";
const BOOKED_DATES_PATH  = "booked-dates.json";
const MANAGE_ELIGIBLE_STATUSES = ["reserved", "reserved_unpaid", "booked_paid", "pending", "pending_checkout", "pending_verification", "approved", "active", "active_rental", "extended", "overdue", "agreement_signed", "pending_manual_payment", "ready_for_pickup"];
// booking_id generated by create-payment-intent.js, e.g. "bk-3bcf479ac6ec".
const BOOKING_REF_PATTERN = /^bk-[a-z0-9]+$/;
const POSTGRES_UNDEFINED_COLUMN_ERROR = "42703";
const POSTGRES_UNDEFINED_TABLE_ERROR = "42P01";
const POSTGREST_SCHEMA_CACHE_ERROR = "PGRST204";
const POSTGREST_EMBEDDED_SCHEMA_ERROR = "PGRST200";
const VERIFY_WINDOW_MS = 15 * 60 * 1000;
const VERIFY_LOCK_MS = 15 * 60 * 1000;
const VERIFY_MAX_ATTEMPTS = 8;
const PARTIAL_BALANCE_PAYMENT_STATUSES = new Set(["partial", "deposit", "deposit_paid", "partially_paid"]);
const BOOKING_SELECT_COLS =
  "id, booking_ref, vehicle_id, pickup_date, return_date, pickup_time, return_time, " +
  "status, payment_status, total_price, deposit_paid, remaining_balance, " +
  "change_count, manage_token, balance_payment_link, pending_change, " +
  "has_protection_plan, protection_plan_tier, category, identity_session_id, " +
  "customer_name, customer_email, customer_phone, payment_intent_id, created_at, " +
  "late_fee_status, late_fee_amount, extension_risk_override";
const BOOKING_SELECT_FALLBACK_COLS =
  "id, booking_ref, vehicle_id, pickup_date, return_date, pickup_time, return_time, " +
  "status, payment_status, total_price, deposit_paid, remaining_balance, " +
  "change_count, category, identity_session_id, customer_name, customer_email, customer_phone, created_at";

export function isMissingColumnCompatError(err, columnName) {
  if (!err) return false;
  const code = String(err.code || "").trim();
  const message = String(err.message || "").toLowerCase();
  const details = String(err.details || "").toLowerCase();
  const hint = String(err.hint || "").toLowerCase();
  const fullText = `${message}\n${details}\n${hint}`;
  const target = String(columnName || "").trim().toLowerCase();
  if (!target) return false;
  if (code === POSTGRES_UNDEFINED_COLUMN_ERROR && fullText.includes(target)) return true;
  if ((code === POSTGREST_SCHEMA_CACHE_ERROR || code === POSTGREST_EMBEDDED_SCHEMA_ERROR) && fullText.includes(target)) return true;
  return fullText.includes("schema cache") && fullText.includes(target);
}

// Best-effort in-memory rate limiting for booking verification attempts.
const verifyAttempts = new Map();


function normalizeLookupPhone(value) {
  const digits = String(value || "").replace(/\D+/g, "");
  if (!digits) return "";
  return digits.length === 11 && digits.startsWith("1") ? digits.slice(1) : digits;
}

function normalizeLookupEmail(value) {
  return String(value || "").trim().toLowerCase();
}

function computeCustomerTier(cust = {}) {
  if (cust.banned) return "risky";
  if (cust.flagged || cust.risk_flag === "high" || Number(cust.no_show_count || 0) >= 2) return "risky";
  const totalProfit = cust.total_profit != null ? Number(cust.total_profit) : null;
  const totalBookings = Number(cust.total_bookings || 0);
  if (totalProfit != null && totalProfit < 0) return "unprofitable";
  if (totalProfit != null && totalProfit >= 500 && totalBookings >= 3) return "vip";
  return "standard";
}

function pickLatestCustomer(rows = []) {
  return [...rows].sort((a, b) => {
    const aUpdated = Date.parse(a?.updated_at || a?.created_at || 0) || 0;
    const bUpdated = Date.parse(b?.updated_at || b?.created_at || 0) || 0;
    return bUpdated - aUpdated;
  })[0] || null;
}

async function resolveCustomerTierForBooking(row) {
  const sb = getSupabaseAdmin();
  if (!sb) return "standard";

  const selectCols = "email, phone, risk_flag, flagged, banned, total_profit, total_bookings, no_show_count, updated_at, created_at";
  const normalizedEmail = normalizeLookupEmail(row?.customer_email);
  const normalizedPhone = normalizeLookupPhone(row?.customer_phone);

  try {
    if (normalizedEmail) {
      const { data, error } = await sb
        .from("customers")
        .select(selectCols)
        .ilike("email", normalizedEmail)
        .order("updated_at", { ascending: false, nullsFirst: false })
        .order("created_at", { ascending: false, nullsFirst: false })
        .limit(10);
      if (!error) {
        const exactMatches = (Array.isArray(data) ? data : [])
          .filter((cust) => normalizeLookupEmail(cust?.email) === normalizedEmail);
        const customer = pickLatestCustomer(exactMatches);
        if (customer) return computeCustomerTier(customer);
      }
    }

    if (normalizedPhone) {
      const phoneCandidates = [...new Set([
        String(row?.customer_phone || "").trim(),
        normalizedPhone,
        `+1${normalizedPhone}`,
      ].filter(Boolean))];

      for (const phoneCandidate of phoneCandidates) {
        const { data, error } = await sb
          .from("customers")
          .select(selectCols)
          .eq("phone", phoneCandidate)
          .order("updated_at", { ascending: false, nullsFirst: false })
          .order("created_at", { ascending: false, nullsFirst: false })
          .limit(10);
        if (error) continue;
        const exactMatches = (Array.isArray(data) ? data : [])
          .filter((cust) => normalizeLookupPhone(cust?.phone) === normalizedPhone);
        const customer = pickLatestCustomer(exactMatches);
        if (customer) return computeCustomerTier(customer);
      }
    }
  } catch (customerErr) {
    console.warn("[manage-booking] customer tier lookup failed (non-fatal):", customerErr.message);
  }

  return "standard";
}

function normalizeLookupBookingIdentifier(value) {
  const trimmed = String(value || "").trim().toLowerCase();
  if (!trimmed) return "";
  if (BOOKING_REF_PATTERN.test(trimmed)) return trimmed;
  // Support legacy/non-bk booking identifiers such as historical hex IDs while
  // avoiding phone-number-only inputs.
  if (/^[a-z0-9_-]{8,64}$/.test(trimmed) && /[a-z]/.test(trimmed)) return trimmed;
  return "";
}

function getClientVerifyKey(req, origin, identifier) {
  const xfwd = String(req.headers["x-forwarded-for"] || "").split(",")[0].trim();
  const ip = xfwd || String(req.socket?.remoteAddress || "unknown");
  const id = String(identifier || "").trim().toLowerCase();
  return `${ip}|${origin || "no-origin"}|${id}`;
}

function readVerifyState(key, now = Date.now()) {
  const current = verifyAttempts.get(key);
  if (!current) return { attempts: [] };
  const attempts = (current.attempts || []).filter((ts) => now - ts <= VERIFY_WINDOW_MS);
  const lockUntil = Number(current.lockUntil || 0);
  if (!attempts.length && lockUntil <= now) {
    verifyAttempts.delete(key);
    return { attempts: [] };
  }
  const normalized = { attempts, lockUntil };
  verifyAttempts.set(key, normalized);
  return normalized;
}

function registerVerifyFailure(key, now = Date.now()) {
  const state = readVerifyState(key, now);
  const attempts = [...(state.attempts || []), now].filter((ts) => now - ts <= VERIFY_WINDOW_MS);
  const next = { attempts };
  if (attempts.length >= VERIFY_MAX_ATTEMPTS) {
    next.lockUntil = now + VERIFY_LOCK_MS;
  }
  verifyAttempts.set(key, next);
  return next;
}

function clearVerifyState(key) {
  verifyAttempts.delete(key);
}

function resolveVisibleLateFeeAmount(lateFeeStatus, lateFeeAmount) {
  const normalizedStatus = String(lateFeeStatus || "").trim().toLowerCase();
  if (normalizedStatus === "dismissed") return null;
  const parsedAmount = Number(lateFeeAmount || 0);
  return parsedAmount > 0 ? parsedAmount : null;
}

function renterOwnsBooking(row, claims) {
  if (!claims) return true;
  const claimBookingRef = String(claims.booking_ref || "").trim().toLowerCase();
  const rowBookingRef = String(row?.booking_ref || "").trim().toLowerCase();
  if (!claimBookingRef || !rowBookingRef || claimBookingRef !== rowBookingRef) return false;
  const claimEmail = String(claims.email || "").trim().toLowerCase();
  if (claimEmail) {
    const rowEmail = String(row?.customer_email || "").trim().toLowerCase();
    if (rowEmail && rowEmail !== claimEmail) return false;
  }
  const claimPhone = normalizeLookupPhone(claims.phone || "");
  if (claimPhone) {
    const rowPhone = normalizeLookupPhone(row?.customer_phone || row?.renter_phone || "");
    if (rowPhone && rowPhone !== claimPhone) return false;
  }
  return true;
}

/**
 * Escape HTML special characters to prevent XSS in email templates.
 */
function esc(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}


/**
 * Lookup a booking row from Supabase by booking_ref (canonical bk-... identifier).
 * Returns null when Supabase is unavailable or the row is not found.
 */
async function fetchBookingFromSupabase(bookingRef) {
  const sb = getSupabaseAdmin();
  if (!sb) return null;
  let selectFallbackUsed = false;
  let result = await sb
    .from("bookings")
    .select(BOOKING_SELECT_COLS)
    .eq("booking_ref", bookingRef)
    .maybeSingle();
  if (
    result.error?.code === POSTGRES_UNDEFINED_COLUMN_ERROR ||
    result.error?.code === POSTGREST_SCHEMA_CACHE_ERROR ||
    result.error?.code === POSTGREST_EMBEDDED_SCHEMA_ERROR
  ) {
    selectFallbackUsed = true;
    result = await sb
      .from("bookings")
      .select(BOOKING_SELECT_FALLBACK_COLS)
      .eq("booking_ref", bookingRef)
      .maybeSingle();
  }
  const { data, error } = result;
  if (error) {
    console.error("[manage-booking] BOOKING_LOOKUP_ERROR: queried booking_ref =", bookingRef, "| error.code =", error.code, "| error.message =", error.message);
    return null;
  }
  if (!data) return null;
  return {
    __selectFallbackUsed: selectFallbackUsed,
    manage_token: null,
    balance_payment_link: "",
    pending_change: null,
    has_protection_plan: false,
    protection_plan_tier: null,
    payment_intent_id: null,
    ...data,
  };
}

async function fetchBookingByPaymentIntentFromSupabase(paymentIntentId) {
  const sb = getSupabaseAdmin();
  if (!sb || !paymentIntentId) return null;
  const { data, error } = await sb
    .from("bookings")
    .select("*")
    .eq("payment_intent_id", paymentIntentId)
    .maybeSingle();
  if (error) {
    console.error("[manage-booking] BOOKING_LOOKUP_ERROR: queried payment_intent_id =", paymentIntentId, "| error.code =", error.code, "| error.message =", error.message);
    return null;
  }
  if (!data) return null;
  return {
    __selectFallbackUsed: false,
    manage_token: null,
    balance_payment_link: "",
    pending_change: null,
    has_protection_plan: false,
    protection_plan_tier: null,
    payment_intent_id: null,
    ...data,
  };
}

async function fetchBookingByIdFromSupabase(bookingPrimaryId) {
  const sb = getSupabaseAdmin();
  if (!sb || !bookingPrimaryId) return null;
  const { data, error } = await sb
    .from("bookings")
    .select("*")
    .eq("id", bookingPrimaryId)
    .maybeSingle();
  if (error) {
    console.error("[manage-booking] BOOKING_LOOKUP_ERROR: queried id =", bookingPrimaryId, "| error.code =", error.code, "| error.message =", error.message);
    return null;
  }
  if (!data) return null;
  return {
    __selectFallbackUsed: false,
    manage_token: null,
    balance_payment_link: "",
    pending_change: null,
    has_protection_plan: false,
    protection_plan_tier: null,
    payment_intent_id: null,
    ...data,
  };
}

/**
 * Load the booked-dates.json ranges for a vehicle from GitHub.
 * Returns an empty array on any error.
 */
async function loadBookedRanges(vehicleId) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) return [];
  try {
    const apiUrl = `https://api.github.com/repos/${GITHUB_REPO}/contents/${BOOKED_DATES_PATH}`;
    const resp = await fetch(`${apiUrl}?ref=${encodeURIComponent(GITHUB_DATA_BRANCH)}`, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
    });
    if (!resp.ok) return [];
    const file = await resp.json();
    const data = JSON.parse(Buffer.from(file.content.replace(/\n/g, ""), "base64").toString("utf-8"));
    return data[vehicleId] || [];
  } catch {
    return [];
  }
}

/**
 * Update the booked-dates.json entry for a vehicle:
 *  1. Remove the old date range (matched by oldFrom/oldTo).
 *  2. Insert the new date range.
 */
async function updateBookedDates(_vehicleId, _oldFrom, _oldTo, _newFrom, _newTo, _newFromTime, _newToTime) {
  // Phase 4: booked-dates.json writes disabled — Supabase is the only write source.
  console.log("manage-booking: updateBookedDates() called but writes are disabled (Phase 4)");
}

/**
 * Compute the effective balance due for a booking row.
 * Guards against data-integrity issues where remaining_balance was stored as 0
 * even though the customer hasn't paid the full amount (e.g. reserved_unpaid
 * bookings where amountPaid was conflated with totalPrice during sync).
 */
function effectiveBalanceDue(row) {
  const totalPrice  = Number(row.total_price   || 0);
  const depositPaid = Number(row.deposit_paid  || 0);
  let   balance     = Number(row.remaining_balance || 0);
  if (balance === 0 && totalPrice > 0 && depositPaid < totalPrice) {
    balance = Math.round((totalPrice - depositPaid) * 100) / 100;
  }
  return balance;
}

function hasPartialBalancePaymentStatus(value) {
  return PARTIAL_BALANCE_PAYMENT_STATUSES.has(
    String(value || "").trim().toLowerCase().replace(/\s+/g, "_")
  );
}

function toObservabilityMoney(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return 0;
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

function logManageBookingContractTransition(eventName, fields = {}, level = "info") {
  const logger = level === "warn" ? console.warn : console.info;
  logger("[manage-booking][contract-transition]", {
    event: eventName,
    ...fields,
  });
}

function buildManageBookingObservability({
  row,
  bookingId,
  resolvedTotal,
  depositPaid,
  balanceDue,
  lifecycle,
  staleBalanceFallbackUsed,
  pricingFallbackUsed,
}) {
  const fallbackPaths = [];
  if (row?.__selectFallbackUsed) {
    fallbackPaths.push({
      path: "supabase_compat_columns",
      source: "bookings_select",
    });
  }
  if (staleBalanceFallbackUsed) {
    fallbackPaths.push({
      path: "remaining_balance_total_minus_paid",
      source: "effectiveBalanceDue",
    });
  }
  if (pricingFallbackUsed) {
    fallbackPaths.push({
      path: "pricing_recompute_for_stale_partial_balance",
      source: "recomputePricing",
    });
  }
  return {
    bookingId,
    canonicalLifecycleState: lifecycle.lifecycleState,
    canonicalFinancialSnapshot: {
      total:   toObservabilityMoney(resolvedTotal),
      paid:    toObservabilityMoney(depositPaid),
      balance: toObservabilityMoney(balanceDue),
    },
    fallbackPaths,
    surfacesUsingLegacyDerivations: ["manage_booking_dashboard"],
  };
}

/**
 * Recompute total and balance_due for a booking after a change.
 * Returns { newTotal, newBalanceDue } or null on unknown vehicle.
 */
async function recomputePricing(vehicleData, pickupDate, returnDate, protectionPlan, protectionPlanTier, depositPaid) {
  const settings = await loadPricingSettings();
  const sb = getSupabaseAdmin();
  if (!sb) return null;
  const pricing = await getVehiclePricing(sb, vehicleData.vehicleId);
  const days = computeRentalDays(pickupDate, returnDate);
  const rentalCost = computeAmountFromPricing(pricing, days);
  console.log('[pricing-booking]', { vehicle: vehicleData.vehicleId, days, pricing, price: rentalCost });
  const dppCost = protectionPlan ? computeDppCostFromSettings(days, protectionPlanTier || null) : 0;
  const preTax = rentalCost + dppCost;
  const newTotal = applyTax(preTax, settings);
  const newBalanceDue = Math.max(0, Math.round((newTotal - depositPaid) * 100) / 100);
  return { newTotal: Math.round(newTotal * 100) / 100, newBalanceDue, settings };
}

/**
 * Build a fresh balance payment link URL.
 * Parameters mirror buildReservationBalanceLink in stripe-webhook.js.
 */
function buildBalanceLink(bookingId, row, vehicleId) {
  const base = "https://slycarrentals.com/balance.html";
  const p = new URLSearchParams();
  const vid = uiVehicleId(vehicleId || row.vehicle_id || "");
  if (vid)                    p.set("v",  vid);
  if (row.pickup_date)        p.set("p",  row.pickup_date);
  if (row.return_date)        p.set("r",  row.return_date);
  if (row.customer_email)     p.set("e",  row.customer_email);
  if (bookingId)              p.set("b",  bookingId);
  if (row.payment_intent_id)  p.set("opi", row.payment_intent_id);
  return `${base}?${p.toString()}`;
}

/**
 * Send the customer an email with the updated balance link after a change.
 */
async function sendChangeConfirmationEmail({
  renterEmail, renterName, vehicleName,
  newPickupDate, newReturnDate,
  newTotal, newBalanceDue, balanceLink,
}) {
  if (!renterEmail || !process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) return;
  try {
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: process.env.SMTP_PORT === "465",
      auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
    });
    const firstName = (renterName || "").split(" ")[0] || "there";
    await transporter.sendMail({
      from: `"Sly Car Rentals LLC" <${process.env.SMTP_USER}>`,
      to: renterEmail,
      subject: "Your Booking Has Been Updated",
      html: `
        <h2>✅ Booking Updated</h2>
        <p>Hi ${esc(firstName)},</p>
        <p>Your booking for <strong>${esc(vehicleName)}</strong> has been updated.</p>
        <table style="border-collapse:collapse;width:100%;margin:16px 0">
          <tr><td style="padding:8px;border:1px solid #ddd"><strong>Pickup</strong></td><td style="padding:8px;border:1px solid #ddd">${esc(newPickupDate)}</td></tr>
          <tr><td style="padding:8px;border:1px solid #ddd"><strong>Return</strong></td><td style="padding:8px;border:1px solid #ddd">${esc(newReturnDate)}</td></tr>
          <tr><td style="padding:8px;border:1px solid #ddd"><strong>New Total</strong></td><td style="padding:8px;border:1px solid #ddd">$${esc(String(newTotal?.toFixed(2)))}</td></tr>
          <tr><td style="padding:8px;border:1px solid #ddd"><strong>Balance Due</strong></td><td style="padding:8px;border:1px solid #ddd">$${esc(String(newBalanceDue?.toFixed(2)))}</td></tr>
        </table>
        <p><a href="${esc(balanceLink)}" style="background:#1a73e8;color:#fff;padding:12px 24px;text-decoration:none;border-radius:4px">Pay Remaining Balance</a></p>
        <p>If you have questions, call us at (844) 511-4059.</p>
      `,
    });
  } catch (emailErr) {
    console.error("manage-booking: change confirmation email failed (non-fatal):", emailErr.message);
  }
}

export default async function handler(req, res) {
  const origin = req.headers.origin;
  if (ALLOWED_ORIGINS.includes(origin)) res.setHeader("Access-Control-Allow-Origin", origin);
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).send("Method Not Allowed");

  const body = req.body || {};
  const { action, token } = body;

  if (!action) return res.status(400).json({ error: "action is required" });

  if (action === "verify") {
    const identifier = String(body.identifier || "").trim();
    if (!identifier) return res.status(400).json({ error: "Phone, email, or booking ID is required." });
    const verifyKey = getClientVerifyKey(req, origin, identifier);
    const verifyNow = Date.now();
    const verifyState = readVerifyState(verifyKey, verifyNow);
    if (verifyState.lockUntil && verifyState.lockUntil > verifyNow) {
      const retryAfterSeconds = Math.max(1, Math.ceil((verifyState.lockUntil - verifyNow) / 1000));
      res.setHeader("Retry-After", String(retryAfterSeconds));
      return res.status(429).json({
        error: "Too many verification attempts. Please try again later.",
        retryAfterSeconds,
      });
    }

    const sb = getSupabaseAdmin();
    if (!sb) return res.status(503).json({ error: "Database unavailable." });

    const lookupEmail = identifier.includes("@") ? identifier.toLowerCase() : "";
    const lookupPhone = normalizeLookupPhone(identifier);
    const lookupBookingIdentifier = normalizeLookupBookingIdentifier(identifier);
    const VERIFY_SELECT_COLS = "id, booking_ref, vehicle_id, customer_email, customer_phone, renter_phone, metadata, created_at";
    const VERIFY_SELECT_FALLBACK_COLS = "id, booking_ref, vehicle_id, customer_email, customer_phone, created_at";
    const baseVerifyQuery = (selectCols) => sb
      .from("bookings")
      .select(selectCols)
      .in("status", MANAGE_ELIGIBLE_STATUSES)
      .order("created_at", { ascending: false })
      .limit(100);
    const runVerifyLookup = async (applyFilter) => {
      let result = await applyFilter(baseVerifyQuery(VERIFY_SELECT_COLS));
      if (result.error?.code === POSTGRES_UNDEFINED_COLUMN_ERROR) {
        result = await applyFilter(baseVerifyQuery(VERIFY_SELECT_FALLBACK_COLS));
      }
      return result;
    };

    let candidates = [];
    let lookupErr = null;
    if (lookupEmail) {
      const result = await runVerifyLookup((q) => q.ilike("customer_email", lookupEmail));
      candidates = result.data || [];
      lookupErr = result.error || null;
    } else if (lookupBookingIdentifier) {
      // Check booking identifier BEFORE phone: booking refs like "bk-3bcf479ac6ec"
      // contain digits which would make lookupPhone truthy, causing the wrong
      // branch to run.
      const result = await runVerifyLookup((q) => q);
      candidates = result.data || [];
      lookupErr = result.error || null;
    } else if (lookupPhone) {
      // Fetch all eligible bookings and normalize in JS — stored phones may have
      // formatting chars (parens, dashes, spaces) that break a substring ilike match.
      const result = await runVerifyLookup((q) => q);
      candidates = result.data || [];
      lookupErr = result.error || null;
    } else {
      candidates = [];
    }
    if (lookupErr) {
      registerVerifyFailure(verifyKey);
      console.error("manage-booking verify lookup error:", lookupErr.message);
      return res.status(500).json({ error: "Could not verify booking right now." });
    }

    const matches = (candidates || []).filter((row) => {
      const metadata = row && typeof row.metadata === "object" && row.metadata ? row.metadata : {};
      const rowEmails = [
        row.customer_email,
        row.renter_email,
        row.email,
        metadata.customer_email,
        metadata.renter_email,
        metadata.email,
      ]
        .map((v) => String(v || "").trim().toLowerCase())
        .filter(Boolean);
      const rowPhones = [
        row.customer_phone,
        row.renter_phone,
        row.phone,
        metadata.customer_phone,
        metadata.renter_phone,
        metadata.phone,
      ]
        .map((v) => normalizeLookupPhone(v))
        .filter(Boolean);
      const rowBookingRef = String(row.booking_ref || "").trim().toLowerCase();
      const rowLegacyId = String(row.id || "").trim().toLowerCase();
      if (lookupEmail)      return rowEmails.includes(lookupEmail);
      // Check booking identifier BEFORE phone so mixed IDs don't get interpreted as phones.
      if (lookupBookingIdentifier) {
        return (!!rowBookingRef && rowBookingRef === lookupBookingIdentifier)
          || (!!rowLegacyId && rowLegacyId === lookupBookingIdentifier);
      }
      if (lookupPhone)      return rowPhones.includes(lookupPhone);
      return false;
    });

    if (!matches.length) {
      registerVerifyFailure(verifyKey);
      return res.status(404).json({ error: "No eligible booking was found with that phone, email, or booking ID." });
    }

    // Use the most recent eligible booking (results are already ordered by created_at desc).
    const selected = matches[0];
    clearVerifyState(verifyKey);

    const selectedBookingIdentifier = String(selected.booking_ref || selected.id || "").trim();
    if (!selectedBookingIdentifier) {
      registerVerifyFailure(verifyKey);
      return res.status(500).json({ error: "Could not verify booking right now." });
    }
    const manageToken = createManageToken(selectedBookingIdentifier);
    const renterSessionToken = createRenterSessionToken({
      bookingRef: selectedBookingIdentifier,
      email: selected.customer_email || "",
      phone: selected.customer_phone || selected.renter_phone || "",
      authMethod: "verify_identifier",
    });
    console.log("[manage-booking] VERIFY: booking_ref =", selectedBookingIdentifier, "| token =", manageToken);
    try {
      await sb
        .from("bookings")
        .update({ manage_token: manageToken, updated_at: new Date().toISOString() })
        .eq("booking_ref", selected.booking_ref || selectedBookingIdentifier);
    } catch (tokenErr) {
      console.warn("manage-booking verify: failed to persist manage token (non-fatal):", tokenErr.message);
    }

    return res.status(200).json({
      verified: true,
      token: manageToken,
      renterSessionToken: renterSessionToken || null,
      bookingId: selectedBookingIdentifier,
      vehicleId: uiVehicleId(selected.vehicle_id || ""),
    });
  }

  const bearerToken = extractBearerToken(req);
  const renterClaims = verifyRenterSessionToken(bearerToken);

  let bookingId = "";
  if (token) {
    bookingId = verifyManageToken(token) || "";
    if (!bookingId) {
      return res.status(401).json({ error: "Invalid or expired manage token. Please verify again, or contact support if your old link no longer works." });
    }
  } else if (renterClaims?.booking_ref) {
    bookingId = String(renterClaims.booking_ref || "").trim();
  } else {
    return res.status(401).json({ error: "manage_token or renter session is required" });
  }

  // ── action: get ─────────────────────────────────────────────────────────────
  if (action === "get") {
    console.log("[manage-booking] TOKEN:", bookingId);

    // 1. Primary lookup: Supabase by booking_ref
    let row = await fetchBookingFromSupabase(bookingId);
    console.log("[manage-booking] GET: fetchBookingFromSupabase(", bookingId, ") =", row ? "FOUND" : "NULL");

    // 2. Safety fallback: Supabase by payment_intent_id
    if (!row) row = await fetchBookingByIdFromSupabase(bookingId);
    if (!row) row = await fetchBookingByPaymentIntentFromSupabase(bookingId);

    // 3. Last-resort fallback: bookings.json (legacy GitHub-stored bookings)
    if (!row) {
      console.warn("[manage-booking] Supabase miss → fallback used", bookingId);
      try {
        const { data } = await loadBookings();
        vehicleLoop: for (const vehicleId of Object.keys(data)) {
          const match = data[vehicleId].find(
            (b) => b.bookingId === bookingId || b.paymentIntentId === bookingId
          );
          if (match) {
            console.warn("[manage-booking] Supabase miss → fallback used", bookingId);
            row = {
              booking_ref:       match.bookingId,
              vehicle_id:        match.vehicleId,
              pickup_date:       match.pickupDate,
              return_date:       match.returnDate,
              pickup_time:       match.pickupTime,
              return_time:       match.returnTime,
              status:            match.status,
              payment_status:    "partial",
              total_price:       match.totalPrice,
              deposit_paid:      match.depositPaid || 0,
              remaining_balance: match.balanceDue  || 0,
              customer_name:     match.name,
              customer_email:    match.email,
              customer_phone:    match.phone,
              change_count:      match.extensionCount || 0,
            };
            break vehicleLoop;
          }
        }
      } catch (jsonErr) {
        console.warn("[manage-booking] bookings.json fallback failed (non-fatal):", jsonErr.message);
      }
    }

    console.log("[manage-booking] RESULT:", row);
    if (!row) return res.status(404).json({ error: "Booking not found" });
    if (!renterOwnsBooking(row, renterClaims)) {
      return res.status(403).json({ error: "Renter session does not match this booking." });
    }

    const vehicleId = uiVehicleId(row.vehicle_id || "");
    const vehicleData = vehicleId ? await getVehicleById(vehicleId) : null;

    // Guard against data-integrity issues where remaining_balance was stored as 0
    // even though the customer hasn't paid the full amount (e.g. reserved_unpaid bookings
    // where amountPaid was conflated with totalPrice during sync).
    const totalPriceNum  = Number(row.total_price   || 0);
    const depositPaidNum = Number(row.deposit_paid  || 0);
    const staleBalanceFallbackUsed = Number(row.remaining_balance || 0) === 0
      && totalPriceNum > 0
      && depositPaidNum < totalPriceNum;
    let balanceDue       = effectiveBalanceDue(row);
    let resolvedTotal    = totalPriceNum;
    let pricingFallbackUsed = false;

    // When remaining_balance is stale zero AND total_price equals the deposit amount
    // (e.g. older bookings where full_rental_amount was absent from PI metadata so
    // the webhook stored total_price = deposit_amount), fall back to live vehicle
    // pricing so the manage-booking dashboard shows the correct outstanding balance
    // and the customer can pay online.  This mirrors the identical fallback already
    // present in the create_balance_payment_intent action below.
    if (balanceDue <= 0 && hasPartialBalancePaymentStatus(row.payment_status) && vehicleData && row.pickup_date && row.return_date) {
      try {
        const repriced = await recomputePricing(
          vehicleData,
          row.pickup_date,
          row.return_date,
          !!row.has_protection_plan,
          row.protection_plan_tier || null,
          depositPaidNum
        );
        if (repriced && repriced.newBalanceDue > 0) {
          balanceDue    = repriced.newBalanceDue;
          resolvedTotal = repriced.newTotal;
          pricingFallbackUsed = true;
        }
      } catch (repErr) {
        console.warn("[manage-booking] get: pricing fallback for stale balance failed (non-fatal):", repErr.message);
      }
    }

    const paymentPlan = await fetchPaymentPlanSummary(getSupabaseAdmin(), bookingId, {
      missingTableErrorCode: POSTGRES_UNDEFINED_TABLE_ERROR,
    });
    const lifecycle = deriveBookingPaymentLifecycle({
      status: row.status,
      paymentStatus: row.payment_status,
      category: row.category,
      totalAmount: resolvedTotal,
      amountPaid: depositPaidNum,
      remainingBalance: balanceDue,
      paymentPlan,
    });
    const contractTransitionObservability = buildManageBookingObservability({
      row,
      bookingId,
      resolvedTotal,
      depositPaid: depositPaidNum,
      balanceDue,
      lifecycle,
      staleBalanceFallbackUsed,
      pricingFallbackUsed,
    });
    if (contractTransitionObservability.fallbackPaths.length > 0) {
      logManageBookingContractTransition("fallback_path_used", {
        booking_id: bookingId,
        fallback_paths: contractTransitionObservability.fallbackPaths,
      });
    }
    logManageBookingContractTransition("legacy_derivation_surface_exposed", {
      booking_id: bookingId,
      surfaces: contractTransitionObservability.surfacesUsingLegacyDerivations,
    });
    const agreementSummary = await loadBookingAgreementSummary(getSupabaseAdmin(), bookingId);
    const customerTier = await resolveCustomerTierForBooking(row);

    // Count how many completed (non-cancelled) bookings this renter has in total,
    // so the frontend can decide whether to show the partial payment option.
    let renterBookingCount = 0;
    const renterEmail = (row.customer_email || "").trim().toLowerCase();
    if (renterEmail) {
      const sb = getSupabaseAdmin();
      if (sb) {
        try {
          const { count } = await sb
            .from("bookings")
            .select("booking_ref", { count: "exact", head: true })
            .ilike("customer_email", renterEmail)
            .not("status", "in", '("cancelled","canceled","rejected","declined")');
          if (Number.isFinite(count)) renterBookingCount = count;
        } catch (countErr) {
          console.warn("[manage-booking] renterBookingCount query failed (non-fatal):", countErr.message);
        }
      }
    }

    return res.status(200).json({
      bookingId,
      vehicleId,
      vehicleName:  vehicleData?.name  || vehicleId,
      vehicleYear:  vehicleData?.year  || null,
      vehicleMake:  vehicleData?.make  || null,
      vehicleModel: vehicleData?.model || null,
      vehicleColor: vehicleData?.color || null,
      pickupDate:  row.pickup_date,
      returnDate:  row.return_date,
      pickupTime:  row.pickup_time,
      returnTime:  row.return_time,
      status:      row.status,
      paymentStatus: row.payment_status,
      category:      row.category || null,
      identitySessionId: row.identity_session_id || null,
      totalPrice:    resolvedTotal,
      depositPaid:   depositPaidNum,
      balanceDue,
      customerName:  row.customer_name || "",
      customerEmail: row.customer_email || "",
      customerPhone: row.customer_phone || "",
      changeCount:   Number(row.change_count  || 0),
      balancePaymentLink: row.balance_payment_link || null,
      hasProtectionPlan: !!row.has_protection_plan,
      protectionPlanTier: row.protection_plan_tier || null,
      paymentPlan,
      paymentLifecycleState: lifecycle.lifecycleState,
      canPayRemainingOnline: lifecycle.canPayRemainingOnline,
      isReservationStage: lifecycle.isReservationStage,
      isActiveRentalStage: lifecycle.isActiveRental,
      isOverdueStage: lifecycle.isOverdue,
      isPickupDueStage: lifecycle.isManualPickup && lifecycle.lifecycleState === "pickup_due",
      lateFeeStatus: row.late_fee_status || null,
      lateFeeAmount: resolveVisibleLateFeeAmount(row.late_fee_status, row.late_fee_amount),
      extensionRiskOverride: row.extension_risk_override || null,
      currentAgreement: agreementSummary.currentAgreement,
      agreements: agreementSummary.agreements,
      contractTransitionObservability,
      customerTier,
      isVipClient: customerTier === "vip",
      renterBookingCount,
    });
  }

  if (action === "create_balance_payment_intent") {
    if (!process.env.STRIPE_SECRET_KEY) {
      return res.status(500).json({ error: "Payment processing is temporarily unavailable. Please contact us at (844) 511-4059." });
    }
    if (!process.env.STRIPE_PUBLISHABLE_KEY) {
      return res.status(500).json({ error: "Payment processing is temporarily unavailable. Please contact us at (844) 511-4059." });
    }
    let row = await fetchBookingFromSupabase(bookingId);
    if (!row) row = await fetchBookingByIdFromSupabase(bookingId);
    if (!row) row = await fetchBookingByPaymentIntentFromSupabase(bookingId);
    if (!row) {
      try {
        const { data } = await loadBookings();
        vehicleLoop: for (const vehicleId of Object.keys(data || {})) {
          const match = (data[vehicleId] || []).find(
            (b) => b.bookingId === bookingId || b.paymentIntentId === bookingId
          );
          if (match) {
            row = {
              booking_ref:       match.bookingId,
              vehicle_id:        match.vehicleId,
              pickup_date:       match.pickupDate,
              return_date:       match.returnDate,
              pickup_time:       match.pickupTime,
              return_time:       match.returnTime,
              status:            match.status,
              payment_status:    "partial",
              total_price:       match.totalPrice,
              deposit_paid:      match.depositPaid || 0,
              remaining_balance: match.balanceDue  || 0,
              customer_name:     match.name,
              customer_email:    match.email,
              customer_phone:    match.phone,
              change_count:      match.extensionCount || 0,
            };
            break vehicleLoop;
          }
        }
      } catch (jsonErr) {
        console.warn("[manage-booking] create_balance_payment_intent: bookings.json fallback failed (non-fatal):", jsonErr.message);
      }
    }
    if (!row) return res.status(404).json({ error: "Booking not found" });
    if (!renterOwnsBooking(row, renterClaims)) {
      return res.status(403).json({ error: "Renter session does not match this booking." });
    }
    const canonicalBookingId = String(row.booking_ref || bookingId || "").trim() || bookingId;
    if (!MANAGE_ELIGIBLE_STATUSES.includes(row.status)) {
      return res.status(409).json({ error: "This booking is not eligible for balance payment." });
    }
    let resolvedBalance = effectiveBalanceDue(row);

    // Load vehicle data early — needed both for the pricing fallback below and
    // for the Stripe PI description / metadata further down.
    const uiVehicle = uiVehicleId(row.vehicle_id || "");
    const vehicleData = uiVehicle ? await getVehicleById(uiVehicle) : null;

    // The booking row fields (total_price, remaining_balance) can be 0 when the
    // balance is tracked exclusively via the ledger system.  Fall back to the
    // ledger's remaining_balance so renters are never incorrectly told there is
    // nothing to pay.
    if (!Number.isFinite(resolvedBalance) || resolvedBalance <= 0) {
      try {
        const ledger = await getLedgerSummary(getSupabaseAdmin(), { bookingId: canonicalBookingId });
        const ledgerBalance = Number(ledger.remaining_balance || 0);
        if (Number.isFinite(ledgerBalance) && ledgerBalance > 0) {
          resolvedBalance = ledgerBalance;
        }
      } catch (ledgerErr) {
        console.warn("[manage-booking] create_balance_payment_intent: ledger fallback failed:", ledgerErr.message);
      }
    }

    // Final fallback: for reservation-deposit bookings where the DB stored
    // total_price = deposit_paid (because full_rental_amount was absent from the
    // PI metadata) and no ledger entry was written, recompute from live pricing
    // so the customer can still pay the outstanding balance online.
    if ((!Number.isFinite(resolvedBalance) || resolvedBalance <= 0) && hasPartialBalancePaymentStatus(row.payment_status) && vehicleData && row.pickup_date && row.return_date) {
      try {
        const repriced = await recomputePricing(
          vehicleData,
          row.pickup_date,
          row.return_date,
          !!row.has_protection_plan,
          row.protection_plan_tier || null,
          Number(row.deposit_paid || 0)
        );
        if (repriced && repriced.newBalanceDue > 0) {
          resolvedBalance = repriced.newBalanceDue;
        }
      } catch (repErr) {
        console.warn("[manage-booking] create_balance_payment_intent: pricing fallback failed:", repErr.message);
      }
    }

    if (!Number.isFinite(resolvedBalance) || resolvedBalance <= 0) {
      return res.status(409).json({ error: "No balance is due for this booking." });
    }

    // Optional partial payment amount — capped server-side to resolvedBalance
    let paymentAmount = resolvedBalance;
    if (body.payment_amount !== undefined && body.payment_amount !== null) {
      const requested = Math.round(Number(body.payment_amount) * 100) / 100;
      if (!Number.isFinite(requested) || requested <= 0) {
        return res.status(400).json({ error: "payment_amount must be a positive number." });
      }
      if (requested > resolvedBalance) {
        return res.status(400).json({
          error: `Payment amount ($${requested.toFixed(2)}) exceeds remaining balance ($${resolvedBalance.toFixed(2)}).`,
        });
      }
      paymentAmount = requested;
    }
    const isPartialPayment = Math.round(paymentAmount * 100) < Math.round(resolvedBalance * 100);
    if (isPartialPayment) {
      const customerTier = await resolveCustomerTierForBooking(row);
      if (customerTier !== "vip") {
        return res.status(403).json({ error: "Partial balance payments are only available to VIP clients." });
      }
    }
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
    const paymentIntent = await stripe.paymentIntents.create({
      amount: Math.round(paymentAmount * 100),
      currency: "usd",
      receipt_email: row.customer_email || undefined,
      description: `Sly Car Rentals LLC – ${vehicleData?.name || uiVehicle || "Rental"} ${isPartialPayment ? "Partial " : ""}Balance Payment`,
      automatic_payment_methods: { enabled: true },
      metadata: {
        payment_type: isPartialPayment ? "partial_balance" : "rental_balance",
        booking_id: canonicalBookingId,
        original_booking_id: canonicalBookingId,
        vehicle_id: uiVehicle || "",
        vehicle_name: vehicleData?.name || uiVehicle || "",
        renter_name: row.customer_name || "",
        renter_phone: row.customer_phone || "",
        email: row.customer_email || "",
        pickup_date: row.pickup_date || "",
        return_date: row.return_date || "",
        remaining_balance: String(resolvedBalance),
        payment_amount: String(paymentAmount),
        remaining_after_payment: isPartialPayment
          ? String(Math.max(0, Math.round((resolvedBalance - paymentAmount) * 100) / 100))
          : "0",
      },
    });
    return res.status(200).json({
      clientSecret: paymentIntent.client_secret,
      publishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
      balanceAmount: resolvedBalance,
      paymentAmount,
      isPartialPayment,
    });
  }

  if (action === "get_agreement_url") {
    const sb = getSupabaseAdmin();
    if (!sb) return res.status(503).json({ error: "Database unavailable" });
    const agreementDetails = await loadAgreementPathForDownload(sb, bookingId);
    if (!agreementDetails?.path) {
      return res.status(404).json({ error: "No agreement PDF found for this booking." });
    }

    const storage = sb.storage?.from?.("rental-agreements");
    if (!storage?.createSignedUrl) {
      return res.status(503).json({ error: "Document storage is unavailable right now." });
    }

    const { data: signedData, error: signedErr } = await storage.createSignedUrl(agreementDetails.path, 3600);
    if (signedErr) {
      console.error("manage-booking agreement signed-url error:", signedErr.message);
      return res.status(500).json({ error: "Could not load the agreement right now." });
    }

    return res.status(200).json({
      url: signedData?.signedUrl || null,
      path: agreementDetails.path,
      currentAgreement: agreementDetails.currentAgreement || null,
      agreements: agreementDetails.agreements || [],
    });
  }

  // ── action: check_availability ──────────────────────────────────────────────
  if (action === "check_availability") {
    const row = await fetchBookingFromSupabase(bookingId);
    if (!row) return res.status(404).json({ error: "Booking not found" });
    if (!renterOwnsBooking(row, renterClaims)) {
      return res.status(403).json({ error: "Renter session does not match this booking." });
    }

    const {
      newPickupDate, newReturnDate,
      newPickupTime, newReturnTime,
      newVehicleId, newProtectionPlan, newProtectionPlanTier,
    } = body;

    if (!newPickupDate || !newReturnDate) {
      return res.status(400).json({ error: "newPickupDate and newReturnDate are required" });
    }

    const targetVehicleUiId = newVehicleId || uiVehicleId(row.vehicle_id || "");
    const vehicleData = await getVehicleById(targetVehicleUiId);
    if (!vehicleData) return res.status(400).json({ error: "Invalid vehicle" });

    // Check availability, excluding this booking's own current range
    const ranges = await loadBookedRanges(targetVehicleUiId);
    const otherRanges = ranges.filter(
      (r) => !(r.from === row.pickup_date && r.to === row.return_date)
    );

    const fPickupTime  = normalizeClockTime(newPickupTime)  || null;
    const fReturnTime  = normalizeClockTime(newReturnTime)  || null;
    const conflict = hasDateTimeOverlap(otherRanges, newPickupDate, newReturnDate, fPickupTime, fReturnTime);

    if (conflict) {
      return res.status(200).json({
        available: false,
        reason: "The requested dates are not available for this vehicle.",
      });
    }

    const depositPaid  = Number(row.deposit_paid || 0);
    const hasProtection = newProtectionPlan !== undefined ? !!newProtectionPlan : false;
    const tier = newProtectionPlanTier || null;

    const pricing = await recomputePricing(vehicleData, newPickupDate, newReturnDate, hasProtection, tier, depositPaid);
    if (!pricing) return res.status(400).json({ error: "Could not compute pricing for this vehicle" });

    const settings = await loadPricingSettings();
    const changeFeeRequired = Number(row.change_count || 0) > 0;
    const changeFee = changeFeeRequired ? (settings.booking_change_fee || 25) : 0;

    return res.status(200).json({
      available: true,
      newTotal:     pricing.newTotal,
      newBalanceDue: pricing.newBalanceDue,
      changeFeeRequired,
      changeFee,
    });
  }

  // ── action: apply_change ────────────────────────────────────────────────────
  if (action === "apply_change") {
    const row = await fetchBookingFromSupabase(bookingId);
    if (!row) return res.status(404).json({ error: "Booking not found" });
    if (!renterOwnsBooking(row, renterClaims)) {
      return res.status(403).json({ error: "Renter session does not match this booking." });
    }

    // Only free (first) changes allowed here
    const changeCount = Number(row.change_count || 0);
    if (changeCount > 0) {
      return res.status(402).json({
        error: "A change fee is required for additional changes.",
        requiresChangeFee: true,
      });
    }

    const {
      newPickupDate, newReturnDate,
      newPickupTime, newReturnTime,
      newVehicleId, newProtectionPlan, newProtectionPlanTier,
    } = body;

    if (!newPickupDate || !newReturnDate) {
      return res.status(400).json({ error: "newPickupDate and newReturnDate are required" });
    }

    const targetVehicleUiId = newVehicleId || uiVehicleId(row.vehicle_id || "");
    const vehicleData = await getVehicleById(targetVehicleUiId);
    if (!vehicleData) return res.status(400).json({ error: "Invalid vehicle" });

    // Availability check (exclude own range)
    const ranges = await loadBookedRanges(targetVehicleUiId);
    const otherRanges = ranges.filter(
      (r) => !(r.from === row.pickup_date && r.to === row.return_date)
    );
    const fPickupTime = normalizeClockTime(newPickupTime) || null;
    const fReturnTime = normalizeClockTime(newReturnTime) || null;
    if (hasDateTimeOverlap(otherRanges, newPickupDate, newReturnDate, fPickupTime, fReturnTime)) {
      return res.status(409).json({ error: "The requested dates are not available for this vehicle." });
    }

    const depositPaid = Number(row.deposit_paid || 0);
    const hasProtection = newProtectionPlan !== undefined ? !!newProtectionPlan : false;
    const tier = newProtectionPlanTier || null;
    const pricing = await recomputePricing(vehicleData, newPickupDate, newReturnDate, hasProtection, tier, depositPaid);
    if (!pricing) return res.status(400).json({ error: "Could not compute pricing for this vehicle" });

    // Build new balance link
    const newBalanceLink = buildBalanceLink(bookingId, {
      ...row,
      pickup_date:      newPickupDate,
      return_date:      newReturnDate,
      vehicle_id:       normalizeVehicleId(targetVehicleUiId),
    }, targetVehicleUiId);

    // Update Supabase bookings row
    const sb = getSupabaseAdmin();
    if (!sb) return res.status(503).json({ error: "Database unavailable" });

    const shouldPersistProtectionPlan = !row.__selectFallbackUsed;

    const applyChangeUpdate = {
      vehicle_id:          normalizeVehicleId(targetVehicleUiId),
      pickup_date:         newPickupDate,
      return_date:         newReturnDate,
      pickup_time:         fPickupTime || row.pickup_time,
      return_time:         fReturnTime || row.return_time,
      total_price:         pricing.newTotal,
      remaining_balance:   pricing.newBalanceDue,
      change_count:        changeCount + 1,
      balance_payment_link: newBalanceLink,
      updated_at:          new Date().toISOString(),
    };
    if (shouldPersistProtectionPlan) {
      applyChangeUpdate.has_protection_plan = hasProtection;
      applyChangeUpdate.protection_plan_tier = hasProtection ? (tier || null) : null;
    }

    let { error: sbErr } = await sb
      .from("bookings")
      .update(applyChangeUpdate)
      .eq("booking_ref", bookingId);

    if (
      sbErr &&
      (isMissingColumnCompatError(sbErr, "has_protection_plan") ||
        isMissingColumnCompatError(sbErr, "protection_plan_tier"))
    ) {
      const legacyApplyChangeUpdate = { ...applyChangeUpdate };
      delete legacyApplyChangeUpdate.has_protection_plan;
      delete legacyApplyChangeUpdate.protection_plan_tier;
      console.warn(
        "manage-booking apply_change retrying update without protection plan columns:",
        sbErr.message
      );
      const retryResult = await sb
        .from("bookings")
        .update(legacyApplyChangeUpdate)
        .eq("booking_ref", bookingId);
      sbErr = retryResult.error || null;
    }

    if (sbErr) {
      console.error(
        "manage-booking apply_change Supabase update error:",
        sbErr.message,
        "| code:", sbErr.code,
        "| details:", sbErr.details,
        "| hint:", sbErr.hint
      );
      return res.status(500).json({ error: "Failed to save booking change" });
    }

    // Update booked-dates.json (disabled, Phase 4 — no-op)
    try {
      await updateBookedDates(
        targetVehicleUiId,
        row.pickup_date, row.return_date,
        newPickupDate, newReturnDate,
        fPickupTime || "", fReturnTime || ""
      );
    } catch (dateErr) {
      console.error("manage-booking apply_change booked-dates update error (non-fatal):", dateErr.message);
    }

    // Sync blocked_dates in Supabase (Phase 4: primary availability source).
    // extendBlockedDateForBooking updates end_date; also update start_date when
    // the pickup date changed (e.g., renter shortens the rental window).
    try {
      await extendBlockedDateForBooking(
        normalizeVehicleId(targetVehicleUiId),
        bookingId,
        newReturnDate,
        fReturnTime || null
      );
      if (newPickupDate !== row.pickup_date && sb) {
        const { error: startUpdateErr } = await sb
          .from("blocked_dates")
          .update({ start_date: newPickupDate })
          .eq("vehicle_id", normalizeVehicleId(targetVehicleUiId))
          .eq("booking_ref", bookingId)
          .eq("reason", "booking");
        if (startUpdateErr) {
          console.warn("manage-booking apply_change blocked_dates start_date update failed (non-fatal):", startUpdateErr.message);
        }
      }
    } catch (blockedErr) {
      console.error("manage-booking apply_change blocked_dates sync error (non-fatal):", blockedErr.message);
    }

    // Update bookings.json (legacy store)
    try {
      const currentVehicleUiId = uiVehicleId(row.vehicle_id || "");
      await updateBooking(currentVehicleUiId, bookingId, {
        vehicleId:           targetVehicleUiId,
        pickupDate:          newPickupDate,
        returnDate:          newReturnDate,
        pickupTime:          fPickupTime || undefined,
        returnTime:          fReturnTime || undefined,
        totalPrice:          pricing.newTotal,
        remainingBalance:    pricing.newBalanceDue,
        balancePaymentLink:  newBalanceLink,
        updatedAt:           new Date().toISOString(),
      });
    } catch (jsonErr) {
      console.error("manage-booking apply_change bookings.json update error (non-fatal):", jsonErr.message);
    }

    // Audit log
    try {
      await writeAuditLog(bookingId, [
        { field: "pickup_date",    oldValue: row.pickup_date,  newValue: newPickupDate },
        { field: "return_date",    oldValue: row.return_date,  newValue: newReturnDate },
        { field: "vehicle_id",     oldValue: row.vehicle_id,   newValue: normalizeVehicleId(targetVehicleUiId) },
        { field: "total_price",    oldValue: String(row.total_price), newValue: String(pricing.newTotal) },
        { field: "remaining_balance", oldValue: String(row.remaining_balance), newValue: String(pricing.newBalanceDue) },
        { field: "change_count",   oldValue: String(changeCount), newValue: String(changeCount + 1) },
      ], "customer");
    } catch (auditErr) {
      console.error("manage-booking apply_change audit log error (non-fatal):", auditErr.message);
    }

    // Send confirmation email
    const updatedRow = await fetchBookingFromSupabase(bookingId);
    if (updatedRow?.customer_email) {
      await sendChangeConfirmationEmail({
        renterEmail:  updatedRow.customer_email,
        renterName:   "",
        vehicleName:  vehicleData.name,
        newPickupDate,
        newReturnDate,
        newTotal:     pricing.newTotal,
        newBalanceDue: pricing.newBalanceDue,
        balanceLink:  newBalanceLink,
      });
    }

    return res.status(200).json({
      success: true,
      newPickupDate,
      newReturnDate,
      newTotal:         pricing.newTotal,
      newBalanceDue:    pricing.newBalanceDue,
      balancePaymentLink: newBalanceLink,
      changeCount:      changeCount + 1,
    });
  }

  // ── action: initiate_paid_change ─────────────────────────────────────────────
  if (action === "initiate_paid_change") {
    if (!process.env.STRIPE_SECRET_KEY) {
      console.error("manage-booking initiate_paid_change: STRIPE_SECRET_KEY is not set");
      return res.status(500).json({ error: "Payment processing is temporarily unavailable. Please contact us at (844) 511-4059." });
    }
    if (!process.env.STRIPE_PUBLISHABLE_KEY) {
      console.error("manage-booking initiate_paid_change: STRIPE_PUBLISHABLE_KEY is not set");
      return res.status(500).json({ error: "Payment processing is temporarily unavailable. Please contact us at (844) 511-4059." });
    }

    const row = await fetchBookingFromSupabase(bookingId);
    if (!row) return res.status(404).json({ error: "Booking not found" });
    if (!renterOwnsBooking(row, renterClaims)) {
      return res.status(403).json({ error: "Renter session does not match this booking." });
    }

    const {
      newPickupDate, newReturnDate,
      newPickupTime, newReturnTime,
      newVehicleId, newProtectionPlan, newProtectionPlanTier,
    } = body;

    if (!newPickupDate || !newReturnDate) {
      return res.status(400).json({ error: "newPickupDate and newReturnDate are required" });
    }

    const targetVehicleUiId = newVehicleId || uiVehicleId(row.vehicle_id || "");
    const vehicleData = await getVehicleById(targetVehicleUiId);
    if (!vehicleData) return res.status(400).json({ error: "Invalid vehicle" });

    // Availability check
    const ranges = await loadBookedRanges(targetVehicleUiId);
    const otherRanges = ranges.filter(
      (r) => !(r.from === row.pickup_date && r.to === row.return_date)
    );
    const fPickupTime = normalizeClockTime(newPickupTime) || null;
    const fReturnTime = normalizeClockTime(newReturnTime) || null;
    if (hasDateTimeOverlap(otherRanges, newPickupDate, newReturnDate, fPickupTime, fReturnTime)) {
      return res.status(409).json({ error: "The requested dates are not available for this vehicle." });
    }

    const settings = await loadPricingSettings();
    const changeFee = settings.booking_change_fee || 25;

    // Persist the pending change to Supabase
    const sb = getSupabaseAdmin();
    if (!sb) return res.status(503).json({ error: "Database unavailable" });

    const pendingChange = {
      newPickupDate, newReturnDate,
      newPickupTime: fPickupTime,
      newReturnTime: fReturnTime,
      newVehicleId:  normalizeVehicleId(targetVehicleUiId),
      newProtectionPlan:   !!newProtectionPlan,
      newProtectionPlanTier: newProtectionPlanTier || null,
      initiatedAt: new Date().toISOString(),
    };

    const { error: sbErr } = await sb
      .from("bookings")
      .update({
        pending_change: pendingChange,
        updated_at: new Date().toISOString(),
      })
      .eq("booking_ref", bookingId);

    if (sbErr) {
      console.error("manage-booking initiate_paid_change Supabase update error:", sbErr.message);
      return res.status(500).json({ error: "Failed to store pending change" });
    }

    // Create Stripe PaymentIntent for the change fee
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
    const paymentIntent = await stripe.paymentIntents.create({
      amount: Math.round(changeFee * 100),
      currency: "usd",
      receipt_email: row.customer_email || undefined,
      description: `Sly Car Rentals LLC – Booking Change Fee (${bookingId})`,
      automatic_payment_methods: { enabled: true },
      metadata: {
        payment_type:    "booking_change_fee",
        booking_id:      bookingId,
        vehicle_id:      normalizeVehicleId(targetVehicleUiId),
        change_fee:      String(changeFee),
      },
    });

    return res.status(200).json({
      clientSecret:    paymentIntent.client_secret,
      publishableKey:  process.env.STRIPE_PUBLISHABLE_KEY,
      changeFee,
    });
  }

  return res.status(400).json({ error: `Unknown action: ${action}` });
}
